version: '3.8'

services:

  db:
    image: "mysql:8.0.40-debian"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    environment:
        MYSQL_ROOT_PASSWORD: arthas
        MYSQL_DATABASE: blizzard
        MYSQL_USER: arthas
        MYSQL_PASSWORD: arthas
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./src/main/resources/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      db:
        condition: service_healthy
        restart: true
