version: '3.8'

services:

  db:
    # Build the image using the Dockerfile in the same directory.
    build: .
    # Needed by mysql, TODO
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    # Not needed here anymore, these are set by the Dockerfile.
    # environment:
    #     MYSQL_ROOT_PASSWORD: hub_talent
    #     MYSQL_DATABASE: hub_talent
    #     MYSQL_USER: hub_talent
    #     MYSQL_PASSWORD: hub_talent
    ports:
      - '3306:3306'
    expose:
      - '3306'
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '8080:8080'
    expose:
      - '8080'
#    depends_on:
#      db:
#        condition: service_healthy
#        restart: true